# Generated by Django 2.2.1 on 2019-05-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treballadors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuari', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('cognoms', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('area', models.CharField(choices=[('SE', 'Serveis Econòmics'), ('ST', 'Serveis Territorials'), ('SP', 'Serveis Personals'), ('SC', 'Seguretat Ciutadana'), ('SI', 'Serveis Interns'), ('SO', 'Serveis Organització')], default='SO', max_length=200)),
                ('rol', models.CharField(choices=[('treb', 'Treballador'), ('resp', 'Responsable'), ('pol', 'Politic')], default='treb', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tramit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacreacio', models.DateTimeField(verbose_name='date published')),
                ('data_sol', models.CharField(max_length=250)),
                ('tipus', models.CharField(choices=[('vacances', 'Vacances'), ('perm_precep', 'Permisos preceptius'), ('perm_no_precep', 'Permisos no preceptius'), ('asum_p', 'Asumptes personals')], default='asum_p', max_length=40)),
                ('valResp', models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=7)),
                ('valPol', models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=7)),
                ('missatge_usuari', models.CharField(max_length=250)),
                ('missatge_responsable', models.CharField(max_length=250)),
                ('treballador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramitador.Treballadors')),
            ],
        ),
    ]
