# Generated by Django 2.2.1 on 2019-07-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramit',
            name='missatge_usuari',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
