# Generated by Django 2.2.1 on 2019-06-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0002_auto_20190606_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramit',
            name='data_sol',
            field=models.CharField(help_text="Interval de dates amb guións '-', per dies no consecutios emprar ',' Exemple:01/01/2019 - 05/01/2019, 07/01/2019", max_length=250),
        ),
        migrations.AlterField(
            model_name='tramit',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramitador.Document'),
        ),
        migrations.AlterField(
            model_name='tramit',
            name='valPol',
            field=models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramit',
            name='valRRHH',
            field=models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramit',
            name='valResp',
            field=models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=20),
        ),
    ]
