# Generated by Django 2.2.1 on 2019-05-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0002_auto_20190528_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramit',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramitador.Document'),
        ),
    ]
