# Generated by Django 2.2.1 on 2019-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0002_auto_20190712_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramit',
            name='data_sol',
            field=models.CharField(help_text="Interval de dates amb guións '/', per dies no consecutios emprar ';' Exemple:2019-08-01-2019-08-20;2019-09-09", max_length=250),
        ),
    ]
