# Generated by Django 2.2.1 on 2019-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0003_auto_20190528_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/'),
        ),
    ]
