# Generated by Django 2.2.1 on 2019-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0003_auto_20190822_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendari',
            name='perm_indisposicio',
            field=models.IntegerField(default=0, verbose_name='Permissos preceptius fets:'),
        ),
        migrations.AddField(
            model_name='calendari',
            name='perm_indisposicio_dies',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
