# Generated by Django 2.2.1 on 2019-06-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0004_calendari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendari',
        ),
    ]
