# Generated by Django 2.2.1 on 2019-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0006_calendari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendari',
            name='asum_p',
            field=models.IntegerField(default=6, verbose_name='Assumptes perosnals disponibles:'),
        ),
        migrations.AlterField(
            model_name='calendari',
            name='perm_no_precep',
            field=models.IntegerField(default=0, verbose_name='Permissos no preceptius fets:'),
        ),
        migrations.AlterField(
            model_name='calendari',
            name='perm_precep',
            field=models.IntegerField(default=0, verbose_name='Permissos preceptius fets:'),
        ),
        migrations.AlterField(
            model_name='calendari',
            name='vacances',
            field=models.IntegerField(default=22, verbose_name='Vacances disponibles'),
        ),
    ]
