# Generated by Django 2.2.1 on 2019-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0007_auto_20190610_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendari',
            name='asum_p_dies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calendari',
            name='perm_no_precep_dies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calendari',
            name='permprecep_dies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calendari',
            name='vacances_dies',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
