# Generated by Django 2.2.1 on 2019-06-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0008_auto_20190611_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendari',
            old_name='permprecep_dies',
            new_name='perm_precep_dies',
        ),
    ]
