# Generated by Django 2.2.1 on 2019-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitador', '0008_auto_20190528_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramit',
            name='valRRHH',
            field=models.CharField(choices=[('conforme', 'conforme'), ('inconforme', 'no conforme'), ('espera', 'en espera')], default='espera', max_length=7),
        ),
    ]
